import { StepCard } from "./types";

export const CARDS: StepCard[] = [
  // ─── DAY 0 — Feb 28 (Saturday): Arrival ───
  {
    slug: "check-in",
    dayNumber: 0,
    dayDate: "2026-02-28",
    sortOrder: 1,
    title: { en: "Check In to Daiwik", hi: "दैविक होटल चेक-इन" },
    subtitle: { en: "Rest & recover from the drive", hi: "ड्राइव के बाद आराम करें" },
    timeWindow: "5:00 – 6:00 PM",
    durationMin: 60,
    icon: "Hotel",
    heroImage: "/images/daiwik-hotel.svg",
    tip: {
      en: "Hotel is 2.5 km from Ramanathaswamy Temple. Auto ride ₹100.",
      hi: "होटल रामनाथस्वामी मंदिर से 2.5 किमी दूर है। ऑटो का किराया ₹100।",
    },
    carry: [],
    skipAllowed: false,
    skipConsequence: null,
    nextSlug: "evening-recon",
    phase: null,
  },
  {
    slug: "evening-recon",
    dayNumber: 0,
    dayDate: "2026-02-28",
    sortOrder: 2,
    title: { en: "Evening Temple Visit", hi: "शाम को मंदिर भ्रमण" },
    subtitle: {
      en: "Corridor walk & orientation only — no bath today",
      hi: "सिर्फ़ गलियारा देखना और पहचान — आज स्नान नहीं",
    },
    timeWindow: "8:00 – 10:30 PM",
    durationMin: 150,
    icon: "Landmark",
    heroImage: "/images/ramanathaswamy-corridor.svg",
    tip: {
      en: "Just a recon walk. Save energy for tomorrow's 8:30 AM start. Dress code: modest Indian attire.",
      hi: "बस पहचान के लिए एक चक्कर लगाना है। कल सुबह 8:30 से असली दर्शन हैं, ताक़त बचाकर रखें। शालीन भारतीय पोशाक पहनें।",
    },
    carry: [
      { en: "Slip-on footwear (no leather)", hi: "स्लिप-ऑन चप्पल (चमड़ा नहीं)" },
    ],
    skipAllowed: true,
    skipConsequence: {
      en: "You'll see the corridors tomorrow but morning will be rushed.",
      hi: "कल सुबह गलियारे देखेंगे लेकिन समय कम होगा।",
    },
    nextSlug: "spatika-lingam",
    phase: null,
  },

  // ─── DAY 1 — Mar 1 (Sunday): Core Darshan Day ───
  {
    slug: "spatika-lingam",
    dayNumber: 1,
    dayDate: "2026-03-01",
    sortOrder: 3,
    title: { en: "Spatika Lingam Darshan", hi: "स्फटिक लिंगम दर्शन" },
    subtitle: {
      en: "Crystal Shiva Lingam by Adi Shankaracharya",
      hi: "आदि शंकराचार्य द्वारा स्थापित स्फटिक शिवलिंग",
    },
    timeWindow: "8:30 – 9:15 AM",
    durationMin: 45,
    icon: "Sparkles",
    heroImage: "/images/spatika-lingam.svg",
    tip: {
      en: "₹50/person ticket at East Gate counter. Reach early to avoid crowd.",
      hi: "पूर्वी गेट काउंटर से ₹50/व्यक्ति का टिकट लें। भीड़ से बचने के लिए जल्दी पहुँचें।",
    },
    carry: [{ en: "₹200 cash (4 tickets)", hi: "₹200 नकद (4 टिकट)" }],
    skipAllowed: true,
    skipConsequence: {
      en: "This is rare and optional. Main darshan sequence is unaffected.",
      hi: "यह एक ख़ास मौक़ा है पर ज़रूरी नहीं। मुख्य दर्शन क्रम पर कोई असर नहीं पड़ेगा।",
    },
    nextSlug: "agni-theertham",
    phase: null,
  },
  {
    slug: "agni-theertham",
    dayNumber: 1,
    dayDate: "2026-03-01",
    sortOrder: 4,
    title: { en: "Agni Theertham", hi: "अग्नि तीर्थम्" },
    subtitle: {
      en: "Sacred sea bath — Phase 1 of 3",
      hi: "पवित्र समुद्र स्नान — चरण 1/3",
    },
    timeWindow: "9:30 – 10:00 AM",
    durationMin: 30,
    icon: "Waves",
    heroImage: "/images/agni-theertham.svg",
    tip: {
      en: "Waves are gentle here. Keep phone & wallet in waterproof pouch. You WILL get fully wet.",
      hi: "यहाँ लहरें हल्की होती हैं। फ़ोन और बटुआ वॉटरप्रूफ़ पाउच में रख लें। पूरे तरह भीगना पड़ेगा।",
    },
    carry: [
      { en: "Waterproof pouch", hi: "वॉटरप्रूफ पाउच" },
      { en: "Change of clothes", hi: "बदलने के कपड़े" },
      { en: "Towel", hi: "तौलिया" },
    ],
    skipAllowed: false,
    skipConsequence: null,
    nextSlug: "22-theerthams",
    phase: "Phase 1 of 3",
  },
  {
    slug: "22-theerthams",
    dayNumber: 1,
    dayDate: "2026-03-01",
    sortOrder: 5,
    title: { en: "22 Theerthams (Bais Kunda)", hi: "22 तीर्थम् (बाइस कुंड स्नान)" },
    subtitle: {
      en: "Sacred wells inside temple — Phase 2 of 3",
      hi: "मंदिर के अंदर पवित्र कुएँ — चरण 2/3",
    },
    timeWindow: "10:00 – 11:30 AM",
    durationMin: 90,
    icon: "Droplets",
    heroImage: "/images/22-theerthams.svg",
    tip: {
      en: "Buy ₹25/person ticket at North Gate BEFORE getting wet at Agni Theertham. Staff pour water from brass pots at each well.",
      hi: "अग्नि तीर्थम में भीगने से पहले नॉर्थ गेट पर ₹25/व्यक्ति टिकट ले लें। हर कुएँ पर कर्मचारी पीतल के बर्तन से पानी डालते हैं।",
    },
    carry: [
      { en: "₹100 cash (4 tickets)", hi: "₹100 नकद (4 टिकट)" },
      { en: "Spare dry clothes for temple", hi: "मंदिर के लिए सूखे कपड़े" },
    ],
    skipAllowed: false,
    skipConsequence: null,
    nextSlug: "main-darshan",
    phase: "Phase 2 of 3",
  },
  {
    slug: "main-darshan",
    dayNumber: 1,
    dayDate: "2026-03-01",
    sortOrder: 6,
    title: { en: "Main Jyotirlinga Darshan", hi: "मुख्य ज्योतिर्लिंग दर्शन" },
    subtitle: { en: "Moolasthana — Phase 3 of 3", hi: "मूलस्थान — चरण 3/3" },
    timeWindow: "11:45 AM – 12:30 PM",
    durationMin: 45,
    icon: "Flame",
    heroImage: "/images/ramanathaswamy-corridor.svg",
    tip: {
      en: "Change into DRY clothes first. ₹200 VIP skip-queue if line is long. NO phones/electronics inside sanctum.",
      hi: "पहले सूखे कपड़े बदल लें। लाइन लंबी हो तो ₹200 में VIP दर्शन ले सकते हैं। गर्भगृह में फ़ोन या कोई भी इलेक्ट्रॉनिक चीज़ ले जाना मना है।",
    },
    carry: [
      { en: "Clean dry clothes (wearing)", hi: "सूखे साफ कपड़े (पहने हुए)" },
      { en: "₹800 cash (4× VIP if needed)", hi: "₹800 नकद (VIP अगर ज़रूरत हो)" },
    ],
    skipAllowed: false,
    skipConsequence: null,
    nextSlug: "rest-hotel",
    phase: "Phase 3 of 3",
  },
  {
    slug: "rest-hotel",
    dayNumber: 1,
    dayDate: "2026-03-01",
    sortOrder: 7,
    title: { en: "Rest at Hotel", hi: "होटल में आराम" },
    subtitle: {
      en: "Mandatory recovery — parents will be drained",
      hi: "ज़रूरी आराम — सुबह की दर्शन यात्रा से थकान होगी",
    },
    timeWindow: "1:00 – 3:00 PM",
    durationMin: 120,
    icon: "BedDouble",
    heroImage: "/images/daiwik-hotel.svg",
    tip: {
      en: "Breakfast at hotel. Don't skip this rest — the afternoon has 3 more stops.",
      hi: "होटल में नाश्ता करें। यह आराम ज़रूर लें — दोपहर बाद अभी 3 और जगहें बाक़ी हैं।",
    },
    carry: [],
    skipAllowed: true,
    skipConsequence: {
      en: "Fatigue will hit hard at Dhanushkodi. Not recommended.",
      hi: "धनुषकोडी में थकान बहुत मारेगी। आराम छोड़ना ठीक नहीं रहेगा।",
    },
    nextSlug: "dhanushkodi",
    phase: null,
  },
  {
    slug: "dhanushkodi",
    dayNumber: 1,
    dayDate: "2026-03-01",
    sortOrder: 8,
    title: { en: "Dhanushkodi", hi: "धनुषकोडी" },
    subtitle: {
      en: "Ram Setu origin + ghost town ruins",
      hi: "राम सेतु का उद्गम स्थल + उजड़े शहर के खंडहर",
    },
    timeWindow: "3:30 – 6:30 PM",
    durationMin: 180,
    icon: "MapPin",
    heroImage: "/images/dhanushkodi.svg",
    tip: {
      en: "20 km from temple. 3-hour round trip. Entry closes 4 PM. Take own car or hire jeep (₹600-800).",
      hi: "मंदिर से 20 किमी दूर। आने-जाने में 3 घंटे। शाम 4 बजे तक प्रवेश। अपनी गाड़ी ले जाएँ या जीप किराए पर लें (₹600-800)।",
    },
    carry: [
      { en: "Water bottles", hi: "पानी की बोतलें" },
      { en: "Sun protection", hi: "धूप से बचाव" },
      { en: "Car keys", hi: "कार की चाबी" },
    ],
    skipAllowed: true,
    skipConsequence: {
      en: "You miss Ram Setu viewpoint and Kothandaramaswamy Temple. Can push to Day 2 morning instead.",
      hi: "राम सेतु व्यू पॉइंट और कोथंडारामस्वामी मंदिर छूट जाएगा। दूसरे दिन सुबह भी जा सकते हैं।",
    },
    nextSlug: "gandhamadana",
    phase: null,
  },
  {
    slug: "gandhamadana",
    dayNumber: 1,
    dayDate: "2026-03-01",
    sortOrder: 9,
    title: { en: "Gandhamadana Parvatham", hi: "गंधमादन पर्वतम्" },
    subtitle: { en: "Lord Rama's footprints", hi: "भगवान राम के पदचिह्न" },
    timeWindow: "8:00 – 8:45 PM",
    durationMin: 45,
    icon: "Footprints",
    heroImage: "/images/gandhamadana.svg",
    tip: {
      en: "~3 km from temple. Quick, low-effort visit. Small hilltop temple.",
      hi: "मंदिर से करीब 3 किमी। जल्दी हो जाएगा, ज़्यादा मेहनत नहीं। पहाड़ी पर छोटा-सा मंदिर है।",
    },
    carry: [],
    skipAllowed: true,
    skipConsequence: {
      en: "Minor site. No impact on main darshan.",
      hi: "छोटी-सी जगह है। मुख्य दर्शन पर कोई फ़र्क़ नहीं पड़ेगा।",
    },
    nextSlug: "panchamukhi-hanuman",
    phase: null,
  },
  {
    slug: "panchamukhi-hanuman",
    dayNumber: 1,
    dayDate: "2026-03-01",
    sortOrder: 10,
    title: { en: "Panchamukhi Hanuman Temple", hi: "पंचमुखी हनुमान मंदिर" },
    subtitle: { en: "Five-faced Hanuman idol", hi: "पाँच मुखों वाली हनुमान प्रतिमा" },
    timeWindow: "8:45 – 9:30 PM",
    durationMin: 45,
    icon: "Shield",
    heroImage: "/images/panchamukhi-hanuman.svg",
    tip: {
      en: "~2 km from main temple. 20-minute visit. Last stop of the day.",
      hi: "मुख्य मंदिर से ~2 किमी। 20 मिनट। दिन का आखिरी पड़ाव।",
    },
    carry: [],
    skipAllowed: true,
    skipConsequence: {
      en: "Minor site. You can visit tomorrow morning in the buffer window.",
      hi: "छोटी-सी जगह है। कल सुबह के खाली समय में जा सकते हैं।",
    },
    nextSlug: "buffer-morning",
    phase: null,
  },

  // ─── DAY 2 — Mar 2 (Monday): Buffer + Return ───
  {
    slug: "buffer-morning",
    dayNumber: 2,
    dayDate: "2026-03-02",
    sortOrder: 11,
    title: { en: "Morning Buffer", hi: "सुबह का खाली समय" },
    subtitle: {
      en: "Revisit temple or catch missed sites",
      hi: "दोबारा मंदिर जाएँ या जो छूट गया वो देख लें",
    },
    timeWindow: "8:00 – 10:00 AM",
    durationMin: 120,
    icon: "Clock",
    heroImage: "/images/ramanathaswamy-corridor.svg",
    tip: {
      en: "Flexible. Use for anything skipped yesterday. Or just relax at hotel.",
      hi: "यह समय खुला है। कल जो छूट गया हो वो कर लें, या होटल में आराम करें।",
    },
    carry: [],
    skipAllowed: true,
    skipConsequence: {
      en: "Straight to Abdul Kalam Memorial or checkout.",
      hi: "सीधे अब्दुल कलाम स्मारक या चेकआउट।",
    },
    nextSlug: "abdul-kalam",
    phase: null,
  },
  {
    slug: "abdul-kalam",
    dayNumber: 2,
    dayDate: "2026-03-02",
    sortOrder: 12,
    title: { en: "Abdul Kalam Memorial", hi: "अब्दुल कलाम स्मारक" },
    subtitle: { en: "Optional — non-religious stop", hi: "वैकल्पिक — धार्मिक स्थल नहीं" },
    timeWindow: "10:30 – 11:00 AM",
    durationMin: 30,
    icon: "GraduationCap",
    heroImage: "/images/abdul-kalam-memorial.svg",
    tip: {
      en: "2.1 km from temple. 30-min visit. Worth it if time allows.",
      hi: "मंदिर से 2.1 किमी दूर। 30 मिनट लगेंगे। समय हो तो ज़रूर जाएँ।",
    },
    carry: [],
    skipAllowed: true,
    skipConsequence: {
      en: "No impact. Head straight to checkout.",
      hi: "कोई असर नहीं। सीधे चेकआउट करें।",
    },
    nextSlug: "checkout-drive",
    phase: null,
  },
  {
    slug: "checkout-drive",
    dayNumber: 2,
    dayDate: "2026-03-02",
    sortOrder: 13,
    title: { en: "Check Out & Drive Home", hi: "चेकआउट और वापसी" },
    subtitle: {
      en: "Rameshwaram → Bengaluru (~9-10 hrs)",
      hi: "रामेश्वरम → बेंगलुरु (~9-10 घंटे)",
    },
    timeWindow: "12:00 PM onwards",
    durationMin: 600,
    icon: "Car",
    heroImage: "/images/daiwik-hotel.svg",
    tip: {
      en: "Pack lunch from hotel. Target arrival: 10-11 PM. Drive safe.",
      hi: "होटल से खाना पैक करवा लें। पहुँचने का लक्ष्य: रात 10-11 बजे। गाड़ी सँभलकर चलाएँ।",
    },
    carry: [
      { en: "Packed lunch & water", hi: "पैक किया खाना और पानी" },
      { en: "CPAP + chargers", hi: "CPAP + चार्जर" },
    ],
    skipAllowed: false,
    skipConsequence: null,
    nextSlug: null,
    phase: null,
  },
];

export function getCardBySlug(slug: string): StepCard | undefined {
  return CARDS.find((c) => c.slug === slug);
}

export function getCardsByDay(day: number): StepCard[] {
  return CARDS.filter((c) => c.dayNumber === day).sort(
    (a, b) => a.sortOrder - b.sortOrder
  );
}

export const DAY_LABELS: Record<number, { en: string; hi: string }> = {
  0: { en: "Day 0 · Feb 28", hi: "दिन 0 · 28 फरवरी" },
  1: { en: "Day 1 · Mar 1", hi: "दिन 1 · 1 मार्च" },
  2: { en: "Day 2 · Mar 2", hi: "दिन 2 · 2 मार्च" },
};
